clean:
	rm -rf *.o
	rm -rf `find . -name *.o`
	rm -rf *.so
	rm -rf abstract_class
	rm -rf functions
	rm -rf functors
	rm -rf object_slicing

all:
	c++ AbstractClass.cpp -o abstract_class
	c++ functions.cpp -o functions
	c++ functors.cpp -o functors
	c++ ObjectSlicing.cpp -o object_slicing
